; This file was auto-generated by drush make
core = 7.26

api = 2

; Modules
projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc4"

projects[auto_entitylabel][subdir] = "contrib"
projects[auto_entitylabel][version] = "1.2"

projects[bean][subdir] = "contrib"
projects[bean][version] = "1.7"

projects[boxes][subdir] = "contrib"
projects[boxes][version] = "1.1"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.3"

projects[cer][subdir] = "contrib"
projects[cer][version] = "2.x-dev"

projects[compact_forms][subdir] = "contrib"
projects[compact_forms][version] = "1.0"

projects[context][subdir] = "contrib"
projects[context][version] = "3.2"

projects[custom_formatters][subdir] = "contrib"
projects[custom_formatters][version] = "2.2"

projects[d3][subdir] = "contrib"
projects[d3][version] = "1.x-dev"

projects[datatables][subdir] = "contrib"
projects[datatables][version] = "1.2"

projects[date][subdir] = "contrib"
projects[date][version] = "2.7"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.4"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[ds][subdir] = "contrib"
projects[ds][version] = "2.6"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.3"
projects[entity][patch][] = http://drupal.org/files/issues/2017685_entity_create_entitycache_tables_10.patch

projects[entitycache][subdir] = "contrib"
projects[entitycache][version] = "1.2"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.1"

projects[features_extra][subdir] = "contrib"
projects[features_extra][version] = "1.0-beta1"

projects[features][subdir] = "contrib"
projects[features][version] = "2.0"

projects[feeds][subdir] = "contrib"
projects[feeds][version] = "2.0-alpha8"

projects[feeds_tamper][subdir] = "contrib"
projects[feeds_tamper][version] = "1.0-beta5"

projects[feeds_xpathparser][subdir] = "contrib"
projects[feeds_xpathparser][version] = "1.0-beta4"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.3"

projects[field_permissions][subdir] = "contrib"
projects[field_permissions][version] = "1.0-beta2"

projects[final_polish][subdir] = "contrib"
projects[final_polish][version] = "1.x-dev"

projects[geofield][subdir] = "contrib"
projects[geofield][version] = "1.2"

projects[geophp][subdir] = "contrib"
projects[geophp][version] = "1.7"

projects[homebox][subdir] = "contrib"
projects[homebox][version] = "2.0-beta7"

projects[i18n][subdir] = "contrib"
projects[i18n][version] = "1.10"

projects[imagecache_token][subdir] = "contrib"
projects[imagecache_token][version] = "1.x-dev"

projects[job_scheduler][subdir] = "contrib"
projects[job_scheduler][version] = "2.0-alpha3"

projects[jquery_colorpicker][version] = "1.0-rc2"

projects[l10n_update][subdir] = "contrib"
projects[l10n_update][version] = "1.0-beta3"

projects[lang_dropdown][subdir] = "contrib"
projects[lang_dropdown][version] = "1.5"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[lightbox2][subdir] = "contrib"
projects[lightbox2][version] = "1.0-beta1"

projects[link][subdir] = "contrib"
projects[link][version] = "1.2"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "1.8"

projects[mongodb][subdir] = "contrib"
projects[mongodb][version] = "1.0-rc2+18-dev"

projects[node_export][subdir] = "contrib"
projects[node_export][version] = "3.0"

projects[openlayers][subdir] = "contrib"
projects[openlayers][version] = "2.0-beta7"

projects[openlayers_plus][subdir] = "contrib"
projects[openlayers_plus][version] = "3.0-beta1"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[pathologic][subdir] = "contrib"
projects[pathologic][version] = "2.12"

projects[plupload][subdir] = "contrib"
projects[plupload][version] = "1.6"

projects[profile2][subdir] = "contrib"
projects[profile2][version] = "1.3"

projects[proj4js][subdir] = "contrib"
projects[proj4js][version] = "1.2"

projects[rabbit_hole][subdir] = "contrib"
projects[rabbit_hole][version] = "2.22"

projects[rules][subdir] = "contrib"
projects[rules][version] = "2.6"

projects[simplenews][subdir] = "contrib"
projects[simplenews][version] = "1.1"

projects[smtp][subdir] = "contrib"
projects[smtp][version] = "1.0"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[themekey][subdir] = "contrib"
projects[themekey][version] = "2.5"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[transliteration][subdir] = "contrib"
projects[transliteration][version] = "3.1"

projects[uuid][subdir] = "contrib"
projects[uuid][version] = "1.0-alpha5"

projects[variable][subdir] = "contrib"
projects[variable][version] = "2.4"

projects[views][subdir] = "contrib"
projects[views][version] = "3.7"

projects[views_slideshow][subdir] = "contrib"
projects[views_slideshow][version] = "3.1"

projects[views_slideshow_xtra][subdir] = "contrib"
projects[views_slideshow_xtra][version] = "3.8"

; Themes
projects[zen][version] = "5.4"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ccis][download][type] = ""
projects[ccis][download][url] = ""
projects[ccis][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[climateparameters][download][type] = ""
projects[climateparameters][download][url] = ""
projects[climateparameters][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[features_aggregator][download][type] = ""
projects[features_aggregator][download][url] = ""
projects[features_aggregator][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[features_user_role_plus][download][type] = ""
projects[features_user_role_plus][download][url] = ""
projects[features_user_role_plus][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ccizen][download][type] = ""
projects[ccizen][download][url] = ""
projects[ccizen][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[d3][download][type] = ""
libraries[d3][download][url] = ""
libraries[d3][directory_name] = "d3"
libraries[d3][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[plupload][download][type] = ""
libraries[plupload][download][url] = ""
libraries[plupload][directory_name] = "plupload"
libraries[plupload][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = ""
libraries[jquery.cycle][download][url] = ""
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorpicker][download][type] = ""
libraries[colorpicker][download][url] = ""
libraries[colorpicker][directory_name] = "colorpicker"
libraries[colorpicker][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[datatables][download][type] = ""
libraries[datatables][download][url] = ""
libraries[datatables][directory_name] = "datatables"
libraries[datatables][type] = "library"

