<?php
/**
 * @file
 * ccis_formatters.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function ccis_formatters_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'date_format_compact';
  $strongarm->value = 'M d, Y';
  $export['date_format_compact'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'date_format_datatable';
  $strongarm->value = 'Y-m-d';
  $export['date_format_datatable'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'date_format_day_only';
  $strongarm->value = 'd';
  $export['date_format_day_only'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'date_format_month_only';
  $strongarm->value = 'F';
  $export['date_format_month_only'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'date_format_year_only';
  $strongarm->value = 'Y';
  $export['date_format_year_only'] = $strongarm;

  return $export;
}
