<?php

/**
 * Implement hook_menu().
 */
function ccis_menu() {
  $items['ccis_dashboard'] = array(
    'title' => 'D3 lab',
    'access callback' => TRUE,
    'page callback' => 'ccis_dashboard_page',
  );
  $items['ccis_datatable'] = array(
    'title' => 'Datatable lab',
    'access callback' => TRUE,
    'page callback' => 'ccis_datatable_page',
  );
  $items['ccis/import'] = array(
    'title' => 'CSV Import',
    'access callback' => TRUE,
    'page callback' => 'ccis_import_page',
  );
  $items['ccis/dataquery/%'] = array(
    'title' => 'Data query',
    'access callback' => TRUE,
    'page callback' => 'ccis_dataquery_page',
    'page arguments' => array(2),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implement hook_block_info().
 */
function ccis_block_info() {
  $blocks['filter'] = array(
    'info' => 'Station Filter',
  );
  $blocks['d3'] = array(
    'info' => 'D3 Graph',
  );
  $blocks['datatables'] = array(
    'info' => 'Datatable',
  );
  return $blocks;
}

/**
 * Implement hook_block_view().
 */
function ccis_block_view($delta) {
  $block = array();
  switch ($delta) {
    case 'filter':
      $block['subject'] = '<none>';
      $block['content'] =  _ccis_block_filter();
      break;
    case 'd3':
      $block['subject'] = '<none>';
      $block['content'] = _ccis_block_d3();
      break;
    case 'datatables':
      $block['subject'] = '<none>';
      $block['content'] = _ccis_block_datatables();
      break;
  }
  return $block;
}

/**
 * Page callback the d3 lab page.
 */
function ccis_dashboard_page() {
  $d3 = libraries_get_path('d3');
  drupal_add_js($d3. '/d3.v3.min.js');
  $path = drupal_get_path('module', 'ccis');
  drupal_add_js($path . '/js/d3.ccis.js');
  return '<div id="ccis_dashboard"></div>';
}

/**
 * Page callback the Datatable lab page.
 */
function ccis_datatable_page() {
  $d3 = libraries_get_path('datatables');
  drupal_add_js($d3. '/media/js/jquery.dataTables.min.js');
  $path = drupal_get_path('module', 'ccis');
  drupal_add_js($path . '/js/datatable.ccis.js');
  return '<div id="ccis_datatables"></div>';
}

/**
 * Page callback to import csv files.
 */
function ccis_import_page() {
  $files = file_scan_directory('private://csv_incoming', '/(\.\.?|\.csv)$/');
  foreach ($files as $file) {
    try{
      $row = 1;
      $header = $end_data = array();
      $header_count = 0;
      if (($handle = fopen($file->uri, "r")) !== FALSE) {
        while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {
          if ($row == 1) {
            $header = $data;
            $header_count = count($header);
          }
          else{
            $data_count = count($data);
            if ($data_count !== $header_count) {
              continue;
            }
            $end_data[] = array_combine($header, $data);
          }
          $row++;
        }
        fclose($handle);
      }
      $col = mongodb_collection($file->name);
      $col->drop();
      $col->batchInsert($end_data);
    }
    catch (Exception $e ) {
      watchdog_exception('ccis', $e);
    }
    drupal_set_message(t('Imported @file', array('@file' => $file->filename)));
    file_unmanaged_delete($file->uri);
  }
  if (empty($files)) {
    drupal_set_message('Did not found any csv files.');
  }
  return '';
}

/**
 * Return the json or csv output of a list.
 * @param string $list
 *   The list name like bremen_daily, bremen_monthly etc.
 * @param string $format
 *   The output format json or csv. Default json.
 */
function ccis_dataquery_page($list, $format = 'json') {
  $supported_formats = array('json', 'csv');
  if (!in_array($format, $supported_formats)) {
    watchdog('ccis', 'Overgiven format: @format is not supported', array('@format' => $format), WATCHDOG_ERROR);
    return MENU_NOT_FOUND;
  }
  try{
    $col = mongodb_collection($list);
    $docs = $col->find();
    $output = $header = array();
    if ($docs->hasNext()) {
      foreach ($docs as $doc) {
        unset($doc['_id']);
        static $tmp;
        if (empty($tmp)) {
          foreach ($doc as $key => $val) {
            $field = field_info_field('field_' . $key);
            if (field_access('view', $field, 'node')) {
              $tmp[$key] = $val;
            }
          }
        }
        foreach ($doc as $key => $val) {
          if (!isset($tmp[$key])) {
            unset($doc[$key]);
          }
        }
        $output[] = $doc;
      }
      if ($format == 'json') {
        drupal_add_http_header('Content-Type', 'application/json; charset=utf-8');
        echo json_encode($output);
      }
      else{
        $header = array_keys(reset($output));
        $output = array_merge(array($header), $output);
        drupal_add_http_header('Content-Type', 'text/csv; charset=utf-8');
        echo _ccis_outputCSV($output);
      }
    }
  }
  catch (Exception $e) {
    watchdog_exception('ccis', $e);
  }
  drupal_exit();
}


/**
 * Copy from http://www.php.net/manual/de/function.fputcsv.php#100033
 */
function _ccis_outputCSV($data) {

  $outstream = fopen("php://output", 'w');

  function __outputCSV(&$vals, $key, $filehandler) {
    fputcsv($filehandler, $vals, ',', '"');
  }
  array_walk($data, '__outputCSV', $outstream);

  fclose($outstream);
}

/**
 * Block output for the filter.
 */
function _ccis_block_filter() {
  $form = drupal_get_form('_ccis_block_filter_form');
  return drupal_render($form);
}

/**
 * Filter form.
 */
function _ccis_block_filter_form($form, $form_state) {
  $form['station'] = array(
    '#title' => t('Station'),
    '#type' => 'textfield',
    '#size' => 5,
  );
  $form['actions'] = array('#type' => 'actions');

  $form['actions']['submit'] = array('#type' => 'submit', '#value' => t('Filter'));
  return $form;
}

/**
 * Submit handler for the form _ccis_block_filter_form().
 */
function _ccis_block_filter_form_submit($form, &$form_state) {
  form_state_values_clean($form_state);
  $form_state['redirect'] = array(current_path(), array('query' => $form_state['values']));
}

/**
 * Block output for the D3 graph.
 */
function _ccis_block_d3() {
  $d3 = libraries_get_path('d3');
  drupal_add_js($d3. '/d3.v3.min.js');
  $path = drupal_get_path('module', 'ccis');
  drupal_add_js($path . '/js/d3.ccis.js');
  return '<h3>D3 Content</h3><div id="ccis_dashboard"></div>';
}

/**
 * Block output for the datatables.
 */
function _ccis_block_datatables() {
  $d3 = libraries_get_path('datatables');
  drupal_add_js($d3. '/media/js/jquery.dataTables.min.js');
  $path = drupal_get_path('module', 'ccis');
  drupal_add_js($path . '/js/datatable.ccis.js');
  return '<h3>DataTables Content</h3><div id="ccis_datatables"></div>';
}